#!/usr/bin/env bash
#
# Usage: sbatch -J <INPUT_FILE> <WRAPPER>
# Description: wrapper script for slurm job submission using 
#              local scratch storage. Output directed to 
#              <INPUT_FILE>.<OUTPUT_EXTENSION>
# Author: tony vo
# Date: 2017-06-13
#
#   1. Specify BINARY (e.g. matlab, g16, python)
#        Example R:
#           Rscript
#
#   2. Specify modules
#        Example CP2K:
#           MODULES=(openmpi/3.1.3 cp2k/5.1)
# 
#   3. Specify OUTPUT_EXTENSION
#        Example STATA:
#           EXTENSION=smcl
#
#   4. Use NSLOTS placeholder rather than explicitly specifying
#      the number of slots. 
#        Example orca:
#           %pal nprocs NSLOTS
#           end
#        Example gaussian:
#           %NProcShared=NSLOTS
#
# Job Options:
#SBATCH --error="error.log"
#SBATCH --output="job.log"
#SBATCH --cpus-per-task=4
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=normal
###


########## BEGIN USER CUSTOMIZATION ########## 

BINARY=orca
MODULES=(orca/4.0.2)
OUTPUT_EXTENSION=out
PROGRAM_OPTIONS=""

########### END USER CUSTOMIZATION ###########

INPUT=$SLURM_JOB_NAME
FILE="${INPUT%.*}"
FILE_EXTENSION="${INPUT#${FILE}.}"
OUTPUT="${FILE}.${OUTPUT_EXTENSION}"
SCRATCH=/scratch
SCRATCH_DIR="${SCRATCH}/${USER}/${SLURM_JOB_ID}"
WORKING_DIR=$PWD


create_job_header() 
{
    ## create log with job metadata
    date +'%a %d %B %Y %H:%M:%S'
    echo "Job ID: $SLURM_JOB_ID"
    echo "Nodes: $SLURM_JOB_NODELIST"
    echo "Working Directory: $WORKING_DIR"
}


create_scratch() 
{
    ## create user scratch directory and populate with program files
    ([[ -d $SCRATCH_DIR ]] || mkdir -p $SCRATCH_DIR) &&
    echo -e "\n  ____ rsync _____"
    rsync -vPa ${WORKING_DIR}/ ${SCRATCH_DIR}/
}


load_module() 
{
    ## load required modules for computation
    source /etc/profile.d/modules.sh &&
    module load "${MODULES[@]}"
}


main()
{
    load_module
    create_job_header
    create_scratch
    run_program
    save_output 
}


run_program() 
{
    ## run program to perform computation on data
    cd $SCRATCH_DIR
    sed -i "s/NSLOTS/${SLURM_CPUS_PER_TASK}/" "${SCRATCH_DIR}/${INPUT}"
    $BINARY $PROGRAM_OPTIONS $INPUT > $OUTPUT
}


save_output() 
{
    ## copy results from scratch to working directory
    rsync -vPa --exclude $INPUT ${SCRATCH_DIR}/ ${WORKING_DIR}/

    ## clean up scratch files
    rm -rf $SCRATCH_DIR
}


main
